# Generated by Django 3.2.16 on 2022-12-21 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_auto_20221221_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
