# Generated by Django 3.2.16 on 2022-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_products_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=32.0853, max_digits=10, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=34.781769, max_digits=11, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
