# Generated by Django 3.2.16 on 2022-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_auto_20221223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Longitude'),
        ),
    ]
