# Generated by Django 3.2.16 on 2022-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_auto_20221223_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Longitude'),
        ),
    ]
