# Generated by Django 3.2.17 on 2023-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_alter_restaurants_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
